#!/bin/python3
import os
import sys
from tree import DeltaException, list_keys, find_ctx, tree_status, cache_status, stash_file, encrypt_file, decrypt_file, init_folder

# Commands

def init(args):
	if find_ctx(fail=False) is not None:
		raise DeltaException("delta root already created.")
	keys = list_keys(True)
	keys.sort(key=lambda x: x["fingerprint"])
	if len(args) == 0:
		if len(keys) == 0:
			raise DeltaException("No keys available.")
		print("Key expected. Key options:")
		for i, key in enumerate(keys):
			print("(%d) =>" % i, key["fingerprint"], key["trust"], key["length"], *key["uids"])
		print("Try again with the number.")
		return
	try:
		index = int(args[0])
	except ValueError:
		raise DeltaException("Invalid number.")
	if index < 0 or index >= len(keys):
		raise DeltaException("Key number not available.")
	key = keys[index]["fingerprint"]
	print("Using key", key)
	init_folder(os.getcwd(), key)
	print("Repo inited.")

def stash(args):
	root, ddir, key = find_ctx()
	print("Delta root:", root)
	link_count, unsaved = tree_status(root)
	if unsaved:
		for f in unsaved:
			stash_file(root, f)
		print("Done stashing!")
	else:
		print("Nothing to stash.")

def encrypt(args):
	root, ddir, key = find_ctx()
	print("Delta root:", root)
	cache_decrypt, cache_encrypt = cache_status(root)
	found_any = False
	for object in cache_decrypt:
		if object not in cache_encrypt:
			found_any = True
			encrypt_file(root, key, object)
	if found_any:
		print("Done encrypting!")
	else:
		print("Nothing to encrypt.")

def decrypt(args):
	root, ddir, key = find_ctx()
	print("Delta root:", root)
	cache_decrypt, cache_encrypt = cache_status(root)
	found_any = False
	for object in cache_encrypt:
		if object not in cache_decrypt:
			found_any = True
			decrypt_file(root, key, object)
	if found_any:
		print("Done decrypting!")
	else:
		print("Nothing to decrypt.")

def status(args):
	root, ddir, key = find_ctx()
	print("Delta root:", root)
	print("Encryption key:", key)
	link_count, unsaved = tree_status(root)
	cache_decrypt, cache_encrypt = cache_status(root)
	cache_needs_encrypt = len([x for x in cache_decrypt if x not in cache_encrypt])
	cache_needs_decrypt = len([x for x in cache_encrypt if x not in cache_decrypt])
	print("Object count:   ", len(cache_decrypt), ("\t+%d" % cache_needs_decrypt) if cache_needs_decrypt else "")
	print("Encrypted count:", len(cache_encrypt), ("\t+%d" % cache_needs_encrypt) if cache_needs_encrypt else "")
	print("Stashed count:  ", link_count, ("\t+%d" % len(unsaved)) if unsaved else "")
	for f in unsaved:
		rel = os.path.relpath(f)
		print("\t%s" % (rel if rel[0:3] == "../" else "./" + rel,))

# Main

if __name__ == "__main__":
	try:
		if len(sys.argv) < 2:
			status([])
		elif sys.argv[1] == "init":
			init(sys.argv[2:])
		elif sys.argv[1] == "status":
			status(sys.argv[2:])
		elif sys.argv[1] == "stash":
			stash(sys.argv[2:])
		elif sys.argv[1] == "encrypt":
			encrypt(sys.argv[2:])
		elif sys.argv[1] == "decrypt":
			decrypt(sys.argv[2:])
		else:
			print("Unknown command %s" % sys.argv[1], file=sys.stderr)
			sys.exit(1)
	except DeltaException as e:
		print("Failed:", str(e))
